# Сравнение результативности разных моделей
Так же используем 41 бинарную классификацию для решения задачи. Категории все разные и могут быть обусловлены разным набором признаков. Поэтому для каждой категории будем рассчитывать результативность предсказания на разных моделях. Так мы поймем, для каких категорий какая модель лучше подходит.

## Загрузка данных

In [ ]:
conda create -n pycaret_env python=3.10 -y

Channels:
 - defaults
Platform: osx-64
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
    current version: 25.5.1
    latest version: 25.7.0

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /opt/anaconda3/envs/pycaret_env

  added / updated specs:
    - python=3.10


The following NEW packages will be INSTALLED:

  bzip2              pkgs/main/osx-64::bzip2-1.0.8-h6c40b1e_6
  ca-certificates    pkgs/main/osx-64::ca-certificates-2025.7.15-hecd8cb5_0
  expat              pkgs/main/osx-64::expat-2.7.1-h6d0c2b6_0
  libcxx             pkgs/main/osx-64::libcxx-19.1.7-haebbb44_3
  libffi             pkgs/main/osx-64::libffi-3.4.4-hecd8cb5_1
  ncurses            pkgs/main/osx-64::ncurses-6.5-h923df54_0
  openssl            pkgs/main/osx-64::openssl-3.0.17-hee2dfae_0
  pip                pkgs/main/noarch::pip-26.0.1-pyhc872135_0
  python             pkgs/main/osx-64::python-3.10.18-hc958d9f_0
  readline           pkgs/main/osx-64::readline-8.3-h49f2429_0
  setuptools         pkgs/main/osx-64::setuptools-78.1.1-py310hecd8cb5_0
  sqlite             pkgs/main/osx-64::sqlite-3.50.2-hc8b0dd6_1
  tk                 pkgs/main/osx-64::tk-8.6.15-h3a5a201_0
  tzdata             pkgs/main/noarch::tzdata-2025c-he532380_0
  wheel              pkgs/main/osx-64::wheel-0.45.1-py310hecd8cb5_0
  xz                 pkgs/main/osx-64::xz-5.6.4-h46256e1_1
  zlib               pkgs/main/osx-64::zlib-1.2.13-h4b97444_1



Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: \

In [1]:
import polars as pl
import polars.selectors as cs

import numpy as np
import matplotlib.pyplot as plt

from catboost import Pool, CatBoostClassifier
from sklearn.metrics import roc_auc_score

from pycaret.classification import ClassificationExperiment

In [2]:
import sklearn
import pycaret
print(sklearn.__version__)
print(pycaret.__version__)

1.4.2
3.3.2

In [5]:
data_path = 'data'

In [6]:
%%time

train = (
    pl
        .scan_parquet(data_path+'/train'+'/train_main_features.parquet')
        # .join(pl.scan_parquet(data_path+'train_extra_features.parquet'), on="customer_id")
        .with_columns(
            cs
                .by_dtype(pl.Float64)
                .cast(pl.Float32)
                # .fill_null(-99999)
        )
        .with_columns(
            cs
                .starts_with("cat_feature_")
                .cast(pl.Int32)
                # .fill_null(-1)
                # .cast(pl.Categorical)
        )
        .collect()
)

train

CPU times: user 968 ms, sys: 3.05 s, total: 4.01 s
Wall time: 1.36 s

shape: (750_000, 200)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ customer_ ┆ cat_featu ┆ cat_featu ┆ cat_featu ┆ … ┆ num_featu ┆ num_featu ┆ num_featu ┆ num_feat │
│ id        ┆ re_1      ┆ re_2      ┆ re_3      ┆   ┆ re_129    ┆ re_130    ┆ re_131    ┆ ure_132  │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ i32       ┆ i32       ┆ i32       ┆ i32       ┆   ┆ f32       ┆ f32       ┆ f32       ┆ f32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1000001   ┆ 1         ┆ 0         ┆ 2         ┆ … ┆ -0.107666 ┆ -0.418616 ┆ null      ┆ null     │
│ 1000002   ┆ 1         ┆ 0         ┆ 0         ┆ … ┆ -0.170724 ┆ -0.805771 ┆ -0.397803 ┆ -0.37373 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
│ 1000003   ┆ 1         ┆ 0         ┆ 0         ┆ … ┆ -0.170724 ┆ -0.602005 ┆ -0.397803 ┆ -0.37373 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
│ 1000004   ┆ 1         ┆ 0         ┆ 2         ┆ … ┆ null      ┆ -0.724265 ┆ null      ┆ null     │
│ 1000005   ┆ 1         ┆ 2         ┆ 0         ┆ … ┆ -0.107666 ┆ null      ┆ -0.397803 ┆ -0.37373 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 1749996   ┆ 1         ┆ 0         ┆ 2         ┆ … ┆ null      ┆ 0.335315  ┆ null      ┆ null     │
│ 1749997   ┆ 1         ┆ 0         ┆ 2         ┆ … ┆ -0.170724 ┆ -0.500123 ┆ null      ┆ null     │
│ 1749998   ┆ 1         ┆ 2         ┆ 0         ┆ … ┆ -0.044607 ┆ null      ┆ 1.128458  ┆ -0.37373 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
│ 1749999   ┆ 1         ┆ 0         ┆ 2         ┆ … ┆ -0.170724 ┆ -0.765018 ┆ null      ┆ null     │
│ 1750000   ┆ 0         ┆ 0         ┆ 2         ┆ … ┆ -0.170724 ┆ -0.622382 ┆ -0.397803 ┆ -0.37373 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [9]:
target = (
    pl
        .read_parquet(data_path+'/baseline'+'/train_target.parquet')
        .with_columns(
            cs
                .starts_with("target_")
                .cast(pl.Boolean)
        )
)

target

shape: (750_000, 42)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ customer_ ┆ target_1_ ┆ target_1_ ┆ target_1_ ┆ … ┆ target_9_ ┆ target_9_ ┆ target_9_ ┆ target_1 │
│ id        ┆ 1         ┆ 2         ┆ 3         ┆   ┆ 6         ┆ 7         ┆ 8         ┆ 0_1      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ i32       ┆ bool      ┆ bool      ┆ bool      ┆   ┆ bool      ┆ bool      ┆ bool      ┆ bool     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1000001   ┆ false     ┆ false     ┆ false     ┆ … ┆ true      ┆ false     ┆ false     ┆ false    │
│ 1000002   ┆ false     ┆ false     ┆ false     ┆ … ┆ false     ┆ false     ┆ false     ┆ false    │
│ 1000003   ┆ false     ┆ false     ┆ false     ┆ … ┆ false     ┆ false     ┆ false     ┆ true     │
│ 1000004   ┆ false     ┆ false     ┆ false     ┆ … ┆ true      ┆ false     ┆ false     ┆ false    │
│ 1000005   ┆ false     ┆ false     ┆ false     ┆ … ┆ false     ┆ false     ┆ false     ┆ true     │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 1749996   ┆ false     ┆ false     ┆ false     ┆ … ┆ false     ┆ false     ┆ false     ┆ false    │
│ 1749997   ┆ false     ┆ false     ┆ false     ┆ … ┆ false     ┆ true      ┆ false     ┆ false    │
│ 1749998   ┆ false     ┆ false     ┆ false     ┆ … ┆ false     ┆ false     ┆ false     ┆ true     │
│ 1749999   ┆ false     ┆ false     ┆ false     ┆ … ┆ true      ┆ false     ┆ false     ┆ false    │
│ 1750000   ┆ false     ┆ false     ┆ false     ┆ … ┆ false     ┆ false     ┆ false     ┆ true     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [10]:
cat_feature_names = [col_name for col_name in train.columns if col_name.startswith("cat_feature")]
#cat_feature_names

CPU times: user 14min, sys: 47 s, total: 14min 47s

Wall time: 2h 17min 15s

## Обучение моделей

In [11]:
%%time

limit = 100_000 #если компьютер шустрый ставь 750_000 
minfrac = 0.1 #Желаемая доля в выборке 
s = ClassificationExperiment()
stats=[]

for target_name in target.columns[1:]:
    print("="*60,target_name)
    
    data = train.sample(limit, shuffle = True, seed = 7
                    ).join(target.select(["customer_id",target_name]),
                              on="customer_id"
                             )#.to_pandas()
    if data[target_name].sum()/limit<minfrac:
        
        data1 = target.select(["customer_id",target_name]
                             ).filter(pl.col(target_name)>0
                                     ).sample( min(round(limit*minfrac), target[target_name].sum()), 
                                              shuffle = True, seed = 7 
                                             )
        data0 = target.select(["customer_id",target_name]
                             ).filter(pl.col(target_name)==0
                                     ).sample( limit-data1.shape[0], 
                                              shuffle = True, seed = 7 
                                             )
        print(data[target_name].sum(), round(limit*minfrac), data1.shape[0], data0.shape[0])
        data = train.sample(limit, 
                             shuffle = True, 
                             seed = 7
                            ).join(pl.concat([data0, data1]),
                                      on="customer_id"
                                     ).drop("customer_id")
    data = data.to_pandas()
    
    #заплатка на глюк polars при переносе категориальных колонок в pandas 
    data[cat_feature_names] = data[cat_feature_names].astype("str")
    
    try:
        s.setup(data, 
            target = target_name, 
            log_experiment=False, 
            experiment_name=target_name
            #use_gpu=True,
           )
        best = s.compare_models(sort = 'AUC')

        leaderboard = s.pull()
        leaderboard.to_csv(f'leaderboard_{target_name}_{limit=}_{minfrac=}')
        stats.append([target_name, 
                      leaderboard.iloc[0].Model,leaderboard.iloc[0].AUC, 
                      leaderboard.iloc[1].Model,leaderboard.iloc[1].AUC, 
                      leaderboard.iloc[2].Model,leaderboard.iloc[2].AUC
                     ]
                    )
        #print(stats)

        s.save_model(best, f'caret_{target_name}_{limit=}_{minfrac=}')
        #break
    except:
        print("Ашипка.")
    
stats = pl.DataFrame(stats, schema=["tcol","model","AUC","model2","AUC2","model3","AUC3"])
stats

============================================================ target_1_1
1045 10000 7797 92203

Transformation Pipeline and Model Successfully Saved
============================================================ target_1_2
314 10000 2569 97431

Transformation Pipeline and Model Successfully Saved
============================================================ target_1_3
2349 10000 10000 90000

Transformation Pipeline and Model Successfully Saved
============================================================ target_1_4
2364 10000 10000 90000

Transformation Pipeline and Model Successfully Saved
============================================================ target_1_5
180 10000 1379 98621

Transformation Pipeline and Model Successfully Saved
============================================================ target_2_1
708 10000 5316 94684

Transformation Pipeline and Model Successfully Saved
============================================================ target_2_2
2483 10000 10000 90000

Transformation Pipeline and Model Successfully Saved
============================================================ target_2_3
131 10000 1041 98959

Transformation Pipeline and Model Successfully Saved
============================================================ target_2_4
750 10000 5677 94323

Transformation Pipeline and Model Successfully Saved
============================================================ target_2_5
201 10000 1421 98579

Transformation Pipeline and Model Successfully Saved
============================================================ target_2_6
446 10000 3305 96695

Transformation Pipeline and Model Successfully Saved
============================================================ target_2_7
38 10000 227 99773

Transformation Pipeline and Model Successfully Saved
============================================================ target_2_8
9 10000 83 99917

Transformation Pipeline and Model Successfully Saved
============================================================ target_3_1
9797 10000 10000 90000

Transformation Pipeline and Model Successfully Saved
============================================================ target_3_2
9784 10000 10000 90000

Transformation Pipeline and Model Successfully Saved
============================================================ target_3_3
111 10000 890 99110

Transformation Pipeline and Model Successfully Saved
============================================================ target_3_4
167 10000 1464 98536

Transformation Pipeline and Model Successfully Saved
============================================================ target_3_5
129 10000 1063 98937

Transformation Pipeline and Model Successfully Saved
============================================================ target_4_1
833 10000 6097 93903

Transformation Pipeline and Model Successfully Saved
============================================================ target_5_1
939 10000 7008 92992

Transformation Pipeline and Model Successfully Saved
============================================================ target_5_2
233 10000 1919 98081

Transformation Pipeline and Model Successfully Saved
============================================================ target_6_1
901 10000 6623 93377

Transformation Pipeline and Model Successfully Saved
============================================================ target_6_2
729 10000 5541 94459

Transformation Pipeline and Model Successfully Saved
============================================================ target_6_3
560 10000 4354 95646

Transformation Pipeline and Model Successfully Saved
============================================================ target_6_4
803 10000 5891 94109

Transformation Pipeline and Model Successfully Saved
============================================================ target_6_5
52 10000 419 99581

Transformation Pipeline and Model Successfully Saved
============================================================ target_7_1
6246 10000 10000 90000

Transformation Pipeline and Model Successfully Saved
============================================================ target_7_2
2715 10000 10000 90000

Transformation Pipeline and Model Successfully Saved
============================================================ target_7_3
407 10000 3184 96816

Transformation Pipeline and Model Successfully Saved
============================================================ target_8_1

Transformation Pipeline and Model Successfully Saved
============================================================ target_8_2
3263 10000 10000 90000

Transformation Pipeline and Model Successfully Saved
============================================================ target_8_3
1846 10000 10000 90000

Transformation Pipeline and Model Successfully Saved
============================================================ target_9_1
349 10000 2726 97274

Transformation Pipeline and Model Successfully Saved
============================================================ target_9_2
3676 10000 10000 90000

Transformation Pipeline and Model Successfully Saved
============================================================ target_9_3
1884 10000 10000 90000

Transformation Pipeline and Model Successfully Saved
============================================================ target_9_4
208 10000 1455 98545

Transformation Pipeline and Model Successfully Saved
============================================================ target_9_5
661 10000 4937 95063

Transformation Pipeline and Model Successfully Saved
============================================================ target_9_6

Transformation Pipeline and Model Successfully Saved
============================================================ target_9_7
7708 10000 10000 90000

Transformation Pipeline and Model Successfully Saved
============================================================ target_9_8
1070 10000 7825 92175

Transformation Pipeline and Model Successfully Saved
============================================================ target_10_1

Transformation Pipeline and Model Successfully Saved
CPU times: user 23min 28s, sys: 10min 10s, total: 33min 39s
Wall time: 3h 33min 38s

shape: (41, 7)
┌─────────────┬────────────┬────────┬──────────────────────┬────────┬─────────────────────┬────────┐
│ tcol        ┆ model      ┆ AUC    ┆ model2               ┆ AUC2   ┆ model3              ┆ AUC3   │
│ ---         ┆ ---        ┆ ---    ┆ ---                  ┆ ---    ┆ ---                 ┆ ---    │
│ str         ┆ str        ┆ f64    ┆ str                  ┆ f64    ┆ str                 ┆ f64    │
╞═════════════╪════════════╪════════╪══════════════════════╪════════╪═════════════════════╪════════╡
│ target_1_1  ┆ CatBoost   ┆ 0.8695 ┆ Random Forest        ┆ 0.8619 ┆ Gradient Boosting   ┆ 0.8578 │
│             ┆ Classifier ┆        ┆ Classifier           ┆        ┆ Classifier          ┆        │
│ target_1_2  ┆ Gradient   ┆ 0.7031 ┆ Logistic Regression  ┆ 0.7004 ┆ Ridge Classifier    ┆ 0.6945 │
│             ┆ Boosting   ┆        ┆                      ┆        ┆                     ┆        │
│             ┆ Classifier ┆        ┆                      ┆        ┆                     ┆        │
│ target_1_3  ┆ Logistic   ┆ 0.7993 ┆ CatBoost Classifier  ┆ 0.7984 ┆ Random Forest       ┆ 0.7955 │
│             ┆ Regression ┆        ┆                      ┆        ┆ Classifier          ┆        │
│ target_1_4  ┆ Logistic   ┆ 0.7469 ┆ Random Forest        ┆ 0.7445 ┆ CatBoost Classifier ┆ 0.7285 │
│             ┆ Regression ┆        ┆ Classifier           ┆        ┆                     ┆        │
│ target_1_5  ┆ CatBoost   ┆ 0.7809 ┆ Gradient Boosting    ┆ 0.7739 ┆ Random Forest       ┆ 0.7635 │
│             ┆ Classifier ┆        ┆ Classifier           ┆        ┆ Classifier          ┆        │
│ …           ┆ …          ┆ …      ┆ …                    ┆ …      ┆ …                   ┆ …      │
│ target_9_5  ┆ Gradient   ┆ 0.7791 ┆ CatBoost Classifier  ┆ 0.7785 ┆ Random Forest       ┆ 0.7669 │
│             ┆ Boosting   ┆        ┆                      ┆        ┆ Classifier          ┆        │
│             ┆ Classifier ┆        ┆                      ┆        ┆                     ┆        │
│ target_9_6  ┆ CatBoost   ┆ 0.6507 ┆ Light Gradient       ┆ 0.6449 ┆ Random Forest       ┆ 0.6397 │
│             ┆ Classifier ┆        ┆ Boosting Machin…     ┆        ┆ Classifier          ┆        │
│ target_9_7  ┆ Logistic   ┆ 0.6879 ┆ Random Forest        ┆ 0.6875 ┆ CatBoost Classifier ┆ 0.6742 │
│             ┆ Regression ┆        ┆ Classifier           ┆        ┆                     ┆        │
│ target_9_8  ┆ CatBoost   ┆ 0.8827 ┆ Gradient Boosting    ┆ 0.8758 ┆ Random Forest       ┆ 0.8677 │
│             ┆ Classifier ┆        ┆ Classifier           ┆        ┆ Classifier          ┆        │
│ target_10_1 ┆ CatBoost   ┆ 0.7305 ┆ Light Gradient       ┆ 0.7286 ┆ Gradient Boosting   ┆ 0.7242 │
│             ┆ Classifier ┆        ┆ Boosting Machin…     ┆        ┆ Classifier          ┆        │
└─────────────┴────────────┴────────┴──────────────────────┴────────┴─────────────────────┴────────┘

## Сохранение результатов

In [12]:
stats.write_csv(f"stats_caret_{limit=}_{minfrac=}.csv")

In [13]:
stats

shape: (41, 7)
┌─────────────┬────────────┬────────┬──────────────────────┬────────┬─────────────────────┬────────┐
│ tcol        ┆ model      ┆ AUC    ┆ model2               ┆ AUC2   ┆ model3              ┆ AUC3   │
│ ---         ┆ ---        ┆ ---    ┆ ---                  ┆ ---    ┆ ---                 ┆ ---    │
│ str         ┆ str        ┆ f64    ┆ str                  ┆ f64    ┆ str                 ┆ f64    │
╞═════════════╪════════════╪════════╪══════════════════════╪════════╪═════════════════════╪════════╡
│ target_1_1  ┆ CatBoost   ┆ 0.8695 ┆ Random Forest        ┆ 0.8619 ┆ Gradient Boosting   ┆ 0.8578 │
│             ┆ Classifier ┆        ┆ Classifier           ┆        ┆ Classifier          ┆        │
│ target_1_2  ┆ Gradient   ┆ 0.7031 ┆ Logistic Regression  ┆ 0.7004 ┆ Ridge Classifier    ┆ 0.6945 │
│             ┆ Boosting   ┆        ┆                      ┆        ┆                     ┆        │
│             ┆ Classifier ┆        ┆                      ┆        ┆                     ┆        │
│ target_1_3  ┆ Logistic   ┆ 0.7993 ┆ CatBoost Classifier  ┆ 0.7984 ┆ Random Forest       ┆ 0.7955 │
│             ┆ Regression ┆        ┆                      ┆        ┆ Classifier          ┆        │
│ target_1_4  ┆ Logistic   ┆ 0.7469 ┆ Random Forest        ┆ 0.7445 ┆ CatBoost Classifier ┆ 0.7285 │
│             ┆ Regression ┆        ┆ Classifier           ┆        ┆                     ┆        │
│ target_1_5  ┆ CatBoost   ┆ 0.7809 ┆ Gradient Boosting    ┆ 0.7739 ┆ Random Forest       ┆ 0.7635 │
│             ┆ Classifier ┆        ┆ Classifier           ┆        ┆ Classifier          ┆        │
│ …           ┆ …          ┆ …      ┆ …                    ┆ …      ┆ …                   ┆ …      │
│ target_9_5  ┆ Gradient   ┆ 0.7791 ┆ CatBoost Classifier  ┆ 0.7785 ┆ Random Forest       ┆ 0.7669 │
│             ┆ Boosting   ┆        ┆                      ┆        ┆ Classifier          ┆        │
│             ┆ Classifier ┆        ┆                      ┆        ┆                     ┆        │
│ target_9_6  ┆ CatBoost   ┆ 0.6507 ┆ Light Gradient       ┆ 0.6449 ┆ Random Forest       ┆ 0.6397 │
│             ┆ Classifier ┆        ┆ Boosting Machin…     ┆        ┆ Classifier          ┆        │
│ target_9_7  ┆ Logistic   ┆ 0.6879 ┆ Random Forest        ┆ 0.6875 ┆ CatBoost Classifier ┆ 0.6742 │
│             ┆ Regression ┆        ┆ Classifier           ┆        ┆                     ┆        │
│ target_9_8  ┆ CatBoost   ┆ 0.8827 ┆ Gradient Boosting    ┆ 0.8758 ┆ Random Forest       ┆ 0.8677 │
│             ┆ Classifier ┆        ┆ Classifier           ┆        ┆ Classifier          ┆        │
│ target_10_1 ┆ CatBoost   ┆ 0.7305 ┆ Light Gradient       ┆ 0.7286 ┆ Gradient Boosting   ┆ 0.7242 │
│             ┆ Classifier ┆        ┆ Boosting Machin…     ┆        ┆ Classifier          ┆        │
└─────────────┴────────────┴────────┴──────────────────────┴────────┴─────────────────────┴────────┘